spring:
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.240.26:3306/dialog_teach_sys?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: dev_user_hust
    password: dev_user_hust
    initialSize: 10   #初始化连接大小
    minIdle: 10   #最小连接池数量
    maxActive: 50 #最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    maxPoolPreparedStatementPerConnectionSize: 50
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL #测试连接
    testWhileIdle: true  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false  #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大,mysql下建议关闭
    filters: stat,wall,log4j2 #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #慢SQL记录
    logSlowSql: true #是否打印sql